name: Actualisation des Données

on:
  workflow_dispatch: # Permet de lancer le robot manuellement

permissions:
  contents: write # CRUCIAL : Donne l'autorisation au robot d'écrire et de sauvegarder dans ton dépôt

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Extraction du produit tendance
        run: python update_data.py

      - name: Sauvegarde et Push du fichier data.json
        run: |
          git config --global user.name "TrendBot"
          git config --global user.email "trendbot@github.com"
          git add data.json
          git commit -m "Mise à jour automatique du produit gagnant 🚀" || echo "Aucun changement détecté"
          git push
